#!/usr/bin/env bash

set -euo pipefail

source "$(dirname ${0})/../lib/utils.sh"

# Simulate tac on macOS
if ! command -v tac &>/dev/null; then
  tac() {
    cat -n "${@}" | sort -nrk1 | cut -f2-
  }
fi

function print_only_fully_numeric_items() {
  local version_numbers="${1}"
  grep -E '^[0-9.]+$' <<< "${version_numbers}"
}

function filter_by_latest_lts_version() {
  local version_numbers="$(cat /dev/stdin)"
  local latest_lts_version='22'
  grep -E "^${latest_lts_version}\." <<< "${version_numbers}"
}

try_to_update_nodebuild >&2

all_definitions_from_node_build="$(nodebuild_wrapped --definitions)"

# Print
echo $(
  print_only_fully_numeric_items "${all_definitions_from_node_build}" \
  | filter_by_latest_lts_version
)
