#!/bin/bash -e

if [ -n "${ASDF_DATA_DIR}" ]; then
    readonly ASDF_INSTALLS_DIR="${ASDF_DATA_DIR}/installs"
else
    readonly ASDF_INSTALLS_DIR="${HOME}/.asdf/installs"
fi

readonly GOLANG_VERSION=${1}
readonly GOLANG_SRC_DIR="${ASDF_INSTALLS_DIR}/golang/${GOLANG_VERSION}/packages/src"

if [[ "${GOLANG_VERSION}" == '1.17.'* ]]; then
    GOIMPORTS_VERSION='v0.16.0'
    GOPLS_VERSION='v0.11.0'
elif [[ "${GOLANG_VERSION}" == '1.18.'* ]]; then
    GOIMPORTS_VERSION='v0.18.0'
    GOPLS_VERSION='v0.14.2'
else
    GOIMPORTS_VERSION='latest'
    GOPLS_VERSION='latest'
fi

CUR_DIR=$(pwd)
TEMP_DIR=$(mktemp -d)

cd ${TEMP_DIR}

asdf local golang ${GOLANG_VERSION}

export GOROOT="${ASDF_INSTALLS_DIR}/golang/${GOLANG_VERSION}/go"
export GOPATH="${ASDF_INSTALLS_DIR}/golang/${GOLANG_VERSION}/packages"

go install golang.org/x/tools/cmd/goimports@${GOIMPORTS_VERSION}
go install golang.org/x/tools/gopls@${GOPLS_VERSION}

unset GOPATH

cd ${CUR_DIR}
rm -rf ${TEMP_DIR}

mkdir -p ${GOLANG_SRC_DIR}
ln -fs $(ghq root)/github.com ${GOLANG_SRC_DIR}/github.com
