#!/bin/bash -e

readonly SCRIPT_DIR=$(cd $(dirname ${0}); pwd)

if [ -n "${ASDF_DATA_DIR}" ]; then
    readonly ASDF_PLUGINS_DIR="${ASDF_DATA_DIR}/plugins"
else
    readonly ASDF_PLUGINS_DIR="${HOME}/.asdf/plugins"
fi

case ${1} in
    gcloud)
        cp ${SCRIPT_DIR}/gcloud-list-all ${ASDF_PLUGINS_DIR}/gcloud/bin/list-all
        ;;
    nodejs)
        cp ${SCRIPT_DIR}/nodejs-list-all ${ASDF_PLUGINS_DIR}/nodejs/bin/list-all
        rm -fr ${ASDF_PLUGINS_DIR}/nodejs/.node-build
        ;;
    python)
        cp ${SCRIPT_DIR}/python-list-all ${ASDF_PLUGINS_DIR}/python/bin/list-all
        rm -fr ${ASDF_PLUGINS_DIR}/python/pyenv
        ;;
    ruby)
        cp ${SCRIPT_DIR}/ruby-list-all ${ASDF_PLUGINS_DIR}/ruby/bin/list-all
        ;;
esac
