#!/usr/bin/env bash

set -euo pipefail

source "$(dirname ${0})/utils.sh"

list_all() {
    install_or_update_python_build
    $(python_build_path) --definitions | grep -E '^[0-9.]+$' | tr '\n' ' '
}

list_all
