set -g prefix C-z

set -g base-index 1
setw -g pane-base-index 1

set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

set -g focus-events on
set -g history-limit 64096

set -g set-titles on
set -g set-titles-string "#T"

unbind-key &
unbind-key 1
unbind-key C-b

bind-key 1 break-pane
bind-key 2 split-window -v
bind-key 3 split-window -h
bind-key k kill-window
bind-key C-k kill-pane
bind-key C-z send-prefix

# claude code
# https://code.claude.com/docs/ja/terminal-config
set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

# disable mouse mode
# set -g mode-mouse off
set -g mouse off
# set -g mouse-resize-pane off
# set -g mouse-select-pane off
# set -g mouse-select-window off

# lazygit / claude code
# https://github.com/craftzdog/dotfiles-public/blob/master/.config/tmux/utility.conf
bind -r g display-popup -d '#{pane_current_path}' -w80% -h80% -E lazygit
bind -r y run-shell '\
  SESSION="claude-$(echo #{pane_current_path} | md5sum | cut -c1-8)"; \
  tmux has-session -t "${SESSION}" 2>/dev/null || \
  tmux new-session -d -s "${SESSION}" -c "#{pane_current_path}" "claude"; \
  tmux display-popup -w80% -h80% -E "tmux attach-session -t ${SESSION}"'

# reattach-to-user-namespace
# https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard
set -g default-command 'reattach-to-user-namespace -l zsh'
bind-key C-c run-shell 'tmux save-buffer - | reattach-to-user-namespace pbcopy'
bind-key C-v run-shell 'reattach-to-user-namespace pbpaste | tmux load-buffer - \; paste-buffer -d'

# undercurl / underline
# https://github.com/leonasdev/.dotfiles/issues/15
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# tmux-themepack
# https://github.com/jimeh/tmux-themepack
# monterey: source-file "${HOME}/ghq/github.com/jimeh/tmux-themepack/powerline/default/purple.tmuxtheme"
# ventura: source-file "${HOME}/ghq/github.com/jimeh/tmux-themepack/powerline/default/orange.tmuxtheme"
# sonoma: source-file "${HOME}/ghq/github.com/jimeh/tmux-themepack/powerline/default/green.tmuxtheme"
# sequoia: source-file "${HOME}/ghq/github.com/jimeh/tmux-themepack/powerline/default/blue.tmuxtheme"
