set -g base-index 1
set -g default-terminal xterm
set -g prefix C-z

unbind-key &
unbind-key 1
unbind-key C-b

bind-key 1 break-pane
bind-key 2 split-window -v
bind-key 3 split-window -h
bind-key C-k kill-pane
bind-key C-z send-prefix
bind-key k kill-window

# claude code
# https://code.claude.com/docs/ja/terminal-config
set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

# disable mouse mode
# set -g mode-mouse off
set -g mouse off
# set -g mouse-resize-pane off
# set -g mouse-select-pane off
# set -g mouse-select-window off

# reattach-to-user-namespace
# https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard
set -g default-command 'reattach-to-user-namespace -l zsh'
bind-key C-c run-shell 'tmux save-buffer - | reattach-to-user-namespace pbcopy'
bind-key C-v run-shell 'reattach-to-user-namespace pbpaste | tmux load-buffer - \; paste-buffer -d'

# tmux-themepack
# https://github.com/jimeh/tmux-themepack
# monterey: source-file "${HOME}/ghq/github.com/jimeh/tmux-themepack/powerline/block/purple.tmuxtheme"
# ventura: source-file "${HOME}/ghq/github.com/jimeh/tmux-themepack/powerline/block/orange.tmuxtheme"
# sonoma: source-file "${HOME}/ghq/github.com/jimeh/tmux-themepack/powerline/block/green.tmuxtheme"
# sequoia: source-file "${HOME}/ghq/github.com/jimeh/tmux-themepack/powerline/block/blue.tmuxtheme"
